version: '3'
services:
  centos7-verilator:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
      args:
      - USER_INIT=user0
    image: centos7-verilator:latest
    container_name: my_verilator
    hostname: my_verilator
    ports:
    - "55000-55100:22"
